---
displayName: Quarkus Postgresql
description: Build and run hotspot or native Quarkus app with postgresql
tags: ["Java", "Quarkus", "OpenJDK", "Maven", "Native", "GraalVM"]
icon: /images/quarkus.svg
