displayName: che-theia
tags: github
globalMemoryLimit: 7Gi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
description: Devfile for https://github.com/eclipse-che/che-theia
links:
  self: /devfiles/eclipse-che-che-theia/devfile.yaml
