displayName: che-devfile-registry
tags: github
globalMemoryLimit: 7Gi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
description: Devfile for https://github.com/eclipse-che/che-devfile-registry
links:
  self: /devfiles/eclipse-che-che-devfile-registry/devfile.yaml
