displayName: theia
tags: github
globalMemoryLimit: 7Gi
icon: https://raw.githubusercontent.com/eclipse-theia/theia/master/logo/theia-logo-no-text-black.svg
description: Devfile for https://github.com/eclipse-theia/theia
links:
  self: /devfiles/eclipse-theia-theia/devfile.yaml
